version: "3.9"

services:
  bd:
    container_name: "my-postgres"
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret

  backend:
    container_name: "backend"
    image: jloperad/praxis-gildedrose_backend:latest
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=bd
    depends_on:
      - bd

  frontend:
    container_name: "frontend"
    image: jloperad/praxis-gildedrose_frontend:latest
    ports:
      - "4200:4200"
    environment:
      - BACKEND_HOST=backend
    depends_on:
      - backend